print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Xike/Documents/Learning Material/DAL/CSCI4168/My4168/Project/The-House/The House/Assets/Models/MaleCharacterPack(1)/Male_walk.mb"`)
{		
	file -o "/Users/Xike/Documents/Learning Material/DAL/CSCI4168/My4168/Project/The-House/The House/Assets/Models/MaleCharacterPack(1)/Male_walk.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Xike/Documents/Learning Material/DAL/CSCI4168/My4168/Project/The-House/The House/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Xike/Documents/Learning Material/DAL/CSCI4168/My4168/Project/The-House/The House/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Xike/Documents/Learning Material/DAL/CSCI4168/My4168/Project/The-House/The House/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
